# Generated by Django 4.0.1 on 2022-02-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_message_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='jpeg_thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
