# Generated by Django 4.0.1 on 2022-06-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_message_message_alter_message_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.TextField(blank=True, null=True)),
                ('group_id', models.TextField(blank=True, null=True)),
                ('message_id', models.TextField(blank=True, null=True)),
                ('listing_type', models.TextField(blank=True, null=True)),
                ('watch_price', models.IntegerField(blank=True, null=True)),
                ('watch_condition', models.TextField(blank=True, null=True)),
                ('watch_year', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('state_name', models.TextField(blank=True, null=True)),
                ('watch_brand', models.TextField(blank=True, null=True)),
                ('watch_model', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('avg_price', models.IntegerField(blank=True, null=True)),
                ('total_listings', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
