# Generated by Django 4.0.1 on 2022-06-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_listing_watch_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watch_price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
