# Generated by Django 4.0.1 on 2022-06-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_listing_watch_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='name_variations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
