# Generated by Django 4.0.1 on 2022-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_watch_name_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('avg_price', models.IntegerField(blank=True, null=True)),
                ('watch_price', models.IntegerField(blank=True, null=True)),
                ('margin_difference', models.IntegerField(blank=True, null=True)),
                ('group_id', models.TextField(blank=True, null=True)),
                ('sender_id', models.TextField(blank=True, null=True)),
                ('sender_name', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('replied', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
