# Generated by Django 4.0.1 on 2022-06-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watch_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
