# Generated by Django 4.0.1 on 2022-06-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_listing_average_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='average_price',
        ),
    ]
