# Generated by Django 4.0.1 on 2022-06-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_listing_average_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='average_price',
        ),
    ]
