# Generated by Django 4.0.1 on 2022-02-08 04:09

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=200)),
                ('sender_id', models.CharField(max_length=200)),
                ('sender_name', models.CharField(max_length=200)),
                ('is_reply', models.BooleanField(null=True)),
                ('user_id', models.CharField(max_length=200)),
                ('message_id', models.CharField(max_length=200)),
                ('message_timestamp', django_unixdatetimefield.fields.UnixDateTimeField(null=True)),
                ('message', models.CharField(max_length=300)),
                ('image_url', models.URLField(null=True)),
                ('image_mimetype', models.CharField(max_length=200, null=True)),
                ('image_height', models.IntegerField(null=True)),
                ('image_width', models.IntegerField(null=True)),
                ('jpeg_thumbnail', models.BinaryField(null=True)),
                ('reply_message_id', models.CharField(max_length=200)),
                ('reply_message_sender_id', models.CharField(max_length=200)),
                ('reply_message_quote', models.CharField(max_length=200)),
            ],
        ),
    ]
