# Generated by Django 4.0.1 on 2022-02-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_message_image_url_alter_message_jpeg_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='group_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_mimetype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_message_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_message_quote',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_message_sender_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.TextField(),
        ),
    ]
